### PR TITLE
Add scijava-plugins-io-table

### PR DESCRIPTION
**Pull request by stelfrich**

### CODE REVIEW

**Comment by ctrueden** [comment]
@stelfrich Could you please also add it to the `dev.scijava` profile?

**Comment by imagejan** [comment]
I meant to submit a PR with concerted version updates to the following components:

* `scijava-plugins-io-table` (this PR)
* `scijava-ui-swing` (pending https://github.com/scijava/scijava-ui-swing/pull/42 and release)
* `imagej-common` (https://github.com/imagej/imagej-common/pull/78 is merged, pending release)
* `imagej-legacy` still requires update PR
* `imagej-omero` still requires update PR

They all don't block the version bump in this PR, but I wanted to make you aware that it's on my radar, and I'm planning to get my part done next week. Before cutting a new release of `pom-scijava`, I think all the above points need to be done first.

**Comment by stelfrich** [comment]
> I meant to submit a PR with concerted version updates to the following components:

Makes sense! Let's close this PR in favor of a single one 👍

**Comment by ctrueden** [comment]
I have some commits locally that update `scijava-ui-swing`, `imagej-common` and `scijava-plugins-io-table`. Will push in a bit.

**Pull request closed without merging**
