### PR TITLE
bump n5, bigdataviewer, bigwarp versions

### PR DESCRIPTION
**Pull request by bogovicj**
* add n5-zstandard

### CODE REVIEW

**Comment by ctrueden** [comment]
The n5-blosc and n5-universe melting pot builds have failing tests. @bogovicj Let me know if you need any help. Otherwise, I will wait for new releases of these components to be added to this PR, to bring everything back into harmony.

**Review by ctrueden — CHANGES_REQUESTED** [review]
The n5-blosc and n5-universe melting pot builds have failing tests. @bogovicj Let me know if you need any help. Otherwise, I will wait for new releases of these components to be added to this PR, to bring everything back into harmony.

**Comment by bogovicj** [comment]
Update: I believe https://github.com/saalfeldlab/n5/pull/113 will fix the n5-blosc issue. 
So far, I'm having trouble reproducing the n5-universe error, but will keep digging..

**Comment by bogovicj** [comment]
[This successful n5-universe build ](https://github.com/saalfeldlab/n5-universe/actions/runs/7805214815/job/21288899736) should be the same as the failing melting pot build.  Not sure what's going on. Need to leave this for now, will revisit tomorrow.

**Comment by bogovicj** [comment]
Good news - the build succeeds now - [this](https://github.com/saalfeldlab/n5/commit/ebd009de08783ae9316707d5bb2e67c50df1a9ea) fixed the n5-blosc issue

Bad news is I'm not sure why the n5-universe build had a test failure last time. Will investigate another day I think

**Pull request merged**
