### PR TITLE
Bump Bio-Formats versions to 6.0.0

### PR DESCRIPTION
**Pull request by sbesson**
Announced on the image.sc forum as https://forum.image.sc/t/release-of-bio-formats-6-0-0/23099

### CODE REVIEW

**Comment by ctrueden** [comment]
@sbesson How is backwards compatilibility with this release? Have you run the melting pot script on sc.fiji:fiji with it?

**Comment by sbesson** [comment]
@ctrueden as per the major version increment, there definitely API breaking changes, mostly at the writer API.

 have not run the melting pot script yet. I will do so probably next week at this hour of the day and report here on my outcome. Is https://github.com/scijava/scijava-scripts/blob/master/melting-pot.sh the right place to start?

**Comment by ctrueden** [comment]
> Is https://github.com/scijava/scijava-scripts/blob/master/melting-pot.sh the right place to start?

There is a script at https://github.com/fiji/fiji/blob/master/bin/melt.sh which calls `melting-pot.sh` with reasonable arguments.

Unfortunately, there are a couple of wrinkles right now which make using it less trivial:

* `net.imagej:imagej-ops` has an unreasonably long build time, due to a bug in javac;
* `sc.fiji:OMEVisual` uses JavaFX and requires Oracle JDK (not OpenJDK) to build;
* IIRC, `org.janelia:H5J_Loader_Plugin` depends on native code so the build only passes on certain platforms.

So lately what I do is:

1. Edit Fiji's `pom.xml` to override whatever versions via the `<properties>` section. In this case, I added `<bio-formats.version>6.0.0</bio-formats.version>`.
2. Run:
    ```
    bin/melt.sh -s
    ```
   Which generates the melting pot but does not run the build.
3. Edit `melting-pot/pom.xml` to comment out the modules that I don't want to include in the compilation, including `imagej-ops`, `OMEVisual` and `H5J_Loader_Plugin`.
4. From the `melting-pot` folder, run `sh build.sh` to build everything.

A future goal is to improve the situation so that it is not necessary to disable any of the above components. As a short-term solution, I could automate those steps into the `bin/melt.sh` script itself. Ideas and suggestions welcome.

I ran the melting-pot locally just now to see how things will be with BF6. I also checked `sc.fiji:OMEVisual` separately using Oracle JDK. Great news: everything compiles with passing tests! :tada:

I found only one problem besides those mentioned above: `ca.mcgill:Sholl_Analysis` fails to build due to an unrelated issue (tferr/ASA#28), which is already fixed on its master branch but not yet released and integrated into Fiji.

So it seems nothing in Fiji relies on any of the old Bio-Formats API, eh?

**Comment by ctrueden** [comment]
I just realized I tested with only `bio-formats.version` updated to 6.0.0... I did not update `ome-common` or `ome-xml` to 6.0.0. I will do that now and rerun the build.

**Comment by ctrueden** [comment]
Builds still pass. ✅ 👍

**Pull request merged**
