### PR TITLE
Bump Bio-Formats version to 7.1.0

### PR DESCRIPTION
**Pull request by dgault**
Bumping to the latest release of Bio-Formats, which includes a number of dependency updates. See [here](https://forum.image.sc/t/release-of-bio-formats-7-1-0/89725) for full details of the changes included.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks!

**Comment by sbesson** [comment]
@ctrueden while on the topic of dependencies, note also that the OME stack starting with Bio-Formats 7.1.0 is migrating to `slf4j-api 2.x/logback 1.3.x` and notably pulling the latest logback releases fixing CVEs.

In the context of the Scijava/Fiji stack, the only required change was to update the component versions in the POMs so the stack should remain compatible with `slf4j-api 1.x` as currently set in https://github.com/scijava/pom-scijava/blob/master/pom.xml#L2261.

**Comment by ctrueden** [comment]
@sbesson Thanks. I'll look into upgrading these dependencies in pom-scijava as well.

About ome-codecs: it appears that version 1.1.0 as mentioned in the release notes does not actually exist? I see a version 1.0.1 released four days ago—is that the latest?

**Comment by dgault** [comment]
@ctrueden, apologies for the confusion, in future I will include all of the component bumps in the same PR

**Pull request merged**
