### PR TITLE
Add OMEVisual

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks!

**Comment by ctrueden** [comment]
I cut a new release `19.1.0` of pom-scijava. Travis should build and deploy it soon. Please update the above PRs to use it when you have time, and then I'll merge them.

**Comment by hadim** [comment]
I am not sure but I think the build fails without Travis complaining about it and so the new version didn't get updated to Maven: https://travis-ci.org/scijava/pom-scijava/builds/331953772

Also for `fiji-javadoc` the Scijava version is set as `RELEASE`. I guess I should let like that right? https://github.com/fiji/fiji-javadoc/blob/master/pom.xml#L11

**Comment by hadim** [comment]
Here is the error:

```
[INFO] [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project pom-scijava: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy failed: 504 - Gateway Timeout -> [Help 1]
```

Seems to be a server connectivity issue...

**Comment by ctrueden** [comment]
> the build fails without Travis complaining about it

FYI, I figured out why that was happening. Now fixed: scijava/scijava-scripts@148638059be8436cfc16805e8f1cc147a4f60816

**Pull request merged**
